language: java
jdk: oraclejdk8
install: true

env: DB=pgsql
<<<<<<< HEAD
# services: postgresql
before_script: psql -c "CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, username VARCHAR(50) UNIQUE, useremail VARCHAR(50) UNIQUE, userpassword TEXT, userscore INTEGER DEFAULT 0); CREATE UNIQUE INDEX users_username_unique_idx ON users (username);" -U postgres;

script: mvn -q -DJDBC_DATABASE_URL=jdbc:postgresql://localhost:5432/postgres clean integration-test
=======
before_script: psql -c "CREATE DATABASE lastunion;" -U postgres;

script: mvn -q clean integration-test
>>>>>>> dev
cache:
  directories: $HOME/.m2