language: java
jdk: oraclejdk8
install: true

env: DB=pgsql
#before_script: psql -c "CREATE DATABASE lastunion;" -U postgres;

script: mvn -q -DJDBC_DATABASE_URL=jdbc:postgresql://localhost:5432/postgres clean integration-test
cache:
  directories: $HOME/.m2