language: java
jdk: oraclejdk8
install: true

env: DB=pgsql
before_script: psql -c "CREATE DATABASE lastunion;" -U postgres;
               psql -c "CREATE USER comp;" -U postgres;
               psql -c "GRANT ALL ON DATABASE lastuinon TO comp;" -U postgres;

script: mvn -q clean integration-test
cache:
  directories: $HOME/.m2